### ISSUE TITLE
installed but not working - maybe interference with another plugin?

### ISSUE THREAD

**Issue by tlawork** [jjpatel361/vscode-reactstrap-snippets#3]
I have installed reactstrap snippets and even restarted the editor.
I have a JS file up and trying the example of row then colmd does not give me any snippet suggestion.

Could this be because of some competing snippet generator I might have enabled?

**Comment by exocode** [comment]
I have the same issue. Couldn't find out what's causing that. 

<img width="337" alt="Bildschirmfoto 2020-02-12 um 18 45 08" src="https://user-images.githubusercontent.com/1597621/74361835-decc8f00-4dc7-11ea-9f0b-a2e82aad1e90.png">
<img width="669" alt="Bildschirmfoto 2020-02-12 um 18 45 34" src="https://user-images.githubusercontent.com/1597621/74361842-e0965280-4dc7-11ea-8824-2cd484a43308.png">

**Comment by jjpatel361** [comment]
Quick way to debug this will be 
- Update VS Code to latest version (_optional but recommended_)
- Disable all extensions installed except `reactstrap-snippets`
- If it doesn't work then this seems a legit problem 
- Go on enabling each of the extensions and confirm if it still works. 

I have a strong suspicion that some extension is overriding the default behavior. 

Also you can enable / disable extension on workspace basis  [VS Code Manage Extensions](https://code.visualstudio.com/docs/editor/extension-gallery)

**Comment by exocode** [comment]
Hm... I disabled all my snippets and reactivated them and it seems it works.. thank you!

**Comment by exocode** [comment]
I found the troublemaker: It's (in my case) the Babel Javascript extension. But what it makes so suspicious is, that only on specific places your extension the snippets are not working_
See here, very curious.
I hope this video will help:

![2020-02-13 12 13 56](https://user-images.githubusercontent.com/1597621/74429594-9199fd00-4e5b-11ea-91ca-07b23c4474fc.gif)




I also link to an issue which is open at vscode-language-babel: 
https://github.com/michaelgmcd/vscode-language-babel/issues/45#issue-417782894

**Comment by michaelgmcd** [comment]
The issue here is that VSCode Language Babel adds two new languages for JSX and JSX Attributes (for several reasons). These snippets need to be applied for those languages as well to be available in JSX. I've created a PR to add support.
